<a href="https://colab.research.google.com/github/ANISHM2004/BIS-lab/blob/main/Parallel_Cellular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from multiprocessing import Pool

N = 100
iterations = 10

grid = np.random.randint(2, size=(N, N))

def compute_next_state(args):
    grid, x, y = args
    neighbors = [
        (x-1, y-1), (x-1, y), (x-1, y+1),
        (x, y-1), (x, y+1),
        (x+1, y-1), (x+1, y), (x+1, y+1),
    ]
    live_neighbors = sum(grid[i % N, j % N] for i, j in neighbors)
    if grid[x, y] == 1:
        return 1 if live_neighbors in (2, 3) else 0
    else:
        return 1 if live_neighbors == 3 else 0

def update_grid(grid):
    args = [(grid, x, y) for x in range(N) for y in range(N)]
    with Pool() as pool:
        new_states = pool.map(compute_next_state, args)
    return np.array(new_states).reshape((N, N))

for _ in range(iterations):
    grid = update_grid(grid)
    print(grid)


[[0 0 0 ... 0 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 0]
 ...
 [1 1 1 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 1]
 ...
 [1 1 1 ... 0 1 1]
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 1 0]
 [1 0 0 ... 1 1 0]]
[[1 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]]
[[1 0 0 ... 1 0 0]
 [1 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 0 1 1]]
[[1 0 0 ... 1 0 0]
 [1 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
[[1 1 0 ... 1 0 0]
 [1 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 0 ... 0 0 1]
 [1 1 0 ... 0 0 1]
 [